### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by agarzon48** [AlvaroMartinFernandez/Conditional-Profile-Card-Generator#1]
Buen trabajo!

Sin embargo, has incluido una funcionalidad que ahora mismo no opera: el botón de contacto.

Punto positivo por lanzarte a ello, pero punto negativo por entregarlo roto 😅 

Ten en cuenta el orden en el que estás ejecutando tu código. El error tiene que ver con algo que hemos comentado en clase varias veces: el hecho de que utilizar innerHTML sobreescribe el HTML interno. A nivel de código es tan solo reorganizar un par de líneas, pero a nivel de concepto es importante que entiendas qué está pasando.

Dale dos vueltas y corrígelo, por favor!

**Comment by AlvaroMartinFernandez** [comment]
Ya esta funcionando no me había dado cuenta que dejaba de funcionar cuando rellenaba uno de los campos.

**Comment by agarzon48** [comment]
Perfect! Pensaba que ya te había pasado feedback, sorry por el retraso!
